### ISSUE TITLE
Does this work with create-react-app?

### ISSUE THREAD

**Issue by bmueller-sykes** [formatjs/babel-plugin-react-intl#108]
I'm pretty sure the answer to my question is "no", but I want to ask it anyway, just to be sure.

So my understanding is that I were to go the `.babelrc` route that when I build a project, I'd wind up with a translations JSON file somewhere in my build folder, which I could then hand off to a translation service.  But after some digging around, it would appear that the only way to get this plugin to work with a `create-react-app`-based app is to eject the app, which I don't want to do.

So given that issue, I *think* the only currently solution is to write a script that I can invoke directly in NodeJS at the command line. I did that, and the code seems to do the right thing (I can share that code, if people want it). 

Obviously, it would be cleaner if this could just be part of the translation process, so I was hoping that I was missing something, and that it could be done with a CRA-based app.

Thanks in advance!

**Comment by evenchange4** [comment]
Related issue: https://github.com/facebookincubator/create-react-app/issues/1227#issuecomment-296316167

**Comment by sunknudsen** [comment]
It’s possible to trigger [babel-plugin-react-intl](https://github.com/yahoo/babel-plugin-react-intl/) manually without ejecting (at least using a recent version of [react-create-app](https://github.com/facebook/create-react-app)).

Also, using [react-intl-translations-manager](https://github.com/GertjanReynaert/react-intl-translations-manager) it’s possible to easily maintain the [translations](https://github.com/yahoo/react-intl/wiki#creating-an-i18n-context) required by [react-intl](https://github.com/yahoo/react-intl).

**Step 1** Install the following packages.

```shell
npm install @babel/cli babel-plugin-react-intl react-intl-translations-manager --save-dev
```

**Step 2** Create a `.babelrc` file in the root directory of your project.

```json
{
  "presets": ["react-app"],
  "plugins": [
    [
      "react-intl", {
        "messagesDir": "translations/messages",
      }
    ]
  ]
}
```

**Step 3**  Create a `translationRunner.js` file in the root directory of your project.

```javascript
const manageTranslations = require('react-intl-translations-manager').default;

manageTranslations({
  messagesDirectory: 'translations/messages',
  translationsDirectory: 'src/translations/locales/',
  languages: ['fr', 'en']
});
```

**Step 4**  Add the following properties (`messages`, `locales` and `translate`) to your `package.json` under `scripts`.

```javascript
{
  "scripts": {
    "messages": "NODE_ENV=production babel src/**/*.tsx >/dev/null",
    "locales": "node ./translationRunner.js",
    "translate": "npm run messages; npm run locales"
  }
}
```

**Step 5** Run `npm run translate` and enjoy life again.

**Comment by glecetre** [comment]
Hello guys,

I am also trying to use react-intl with a create-react-app (with TypeScript), and I tried what your mention @sunknudsen, but it doesn't extract my messages. Shouldn't it?

For now I try it on only one component which uses `defineMessages` (from package `react-intl`).

Could you provide more information please?

**Comment by sunknudsen** [comment]
@glecetre I personally use the `FormattedMessage` component vs `defineMessages`. Have you tried this approach?

```tsx
<FormattedMessage
  id="about.description"
  defaultMessage="Lickstats is..."
/>
```

**Comment by glecetre** [comment]
Nope, doesn't work either. I suspect that nothing is even happening in Babel, the console output is completely empty except for the translation manager:

![image](https://user-images.githubusercontent.com/43233602/53039841-5fd89b00-3480-11e9-9fb9-3b3797893a35.png)

I also tried with npm instead of yarn, just in case, but with no success.

**Comment by sunknudsen** [comment]
@glecetre Can you please share a screenshot of the folders and files in your project? Anything under `translations` either in the root of the project or in `src`?

**Comment by guy-blockchain** [comment]
This worked for me:

https://github.com/facebook/create-react-app/issues/1227#issuecomment-297604621

**Comment by jamieallen59** [comment]
I was having lots of problems with this so [wrote a post here](https://medium.com/@jamieallen59/using-react-intl-with-create-react-app-6667ee3e19f3) for using react-intl, babel-plugin-react-intl and create-react-app.

**Comment by rlahoda** [comment]
@jamieallen59 Thanks for writing that post! It finally got me working.

**Comment by longlho** [comment]
close due to stale
