### ISSUE TITLE
How do I know if the plugin is running?

### ISSUE THREAD

**Issue by giroplus** [formatjs/babel-plugin-react-intl#111]
I have installed this plugin, I have added this to my package.json:
```
`"babel": {
    "plugins": [
      "transform-class-properties",
      ["react-intl", {
        "messagesDir": "/*absolutepath*/lib/messages"
      }]
    ]
  },`
```
 I am using this plugin with meteor.

But nothing happens, and I just do not know where to start troubleshooting?

**Comment by RickWong** [comment]
I had the same issue. I was using `require()` syntax to load `defineMessages` instead of `import` (ES6).

**Comment by longlho** [comment]
close due to stale
