### ISSUE TITLE
Support other props extraction

### ISSUE THREAD

**Issue by geekyme** [formatjs/babel-plugin-react-intl#112]
At the moment this plugin only extracts `id`, `defaultMessage`, `description`. It would be better if I can specify other props to extract from `FormattedMessage` and `defineMessages`. 

Use case = defining screenshots, specifying WIP strings, etc.

**Comment by geekyme** [comment]
@zillding

**Comment by coluccini** [comment]
+1 to this.

**Comment by longlho** [comment]
See #105 for context
