### ISSUE TITLE
Support multiple "moduleSourceName"

### ISSUE THREAD

**Issue by Bazze** [formatjs/babel-plugin-react-intl#113]
Hello!

We want to start using [react-intl-phraseapp](https://github.com/phrase/react-intl-phraseapp) but it doesn't play nice with this babel plugin, more info in https://github.com/phrase/react-intl-phraseapp/issues/2. The issue is that it wraps a few of the React components, but doesn't export e.g. the `defineMessages` function. 

One solution to this is that we could change `moduleSourceName` to support multiple values in the configuration for this plugin. What do you think of that idea?

Thanks

**Comment by longlho** [comment]
close due to stale
