### ISSUE TITLE
JSXOpeningElement not being visited

### ISSUE THREAD

**Issue by Kronuz** [formatjs/babel-plugin-react-intl#118]
In my project, for some reason, `JSXOpeningElement` isn't being visited for all elements (any idea?); however on those, `JSXElement` does get visited.

I fixed things here by also adding a `JSXElement` visitor which basically just calls `JSXOpeningElement`:

```es6
JSXElement(path, state) {
    _JSXOpeningElement(path.get('openingElement'), state);
},
JSXOpeningElement(path, state) {
    _JSXOpeningElement(path, state);
},
```

**Comment by longlho** [comment]
`FormattedMessage` is a self-closing tag which is prob the reason why this happens
