### ISSUE TITLE
Error: "Messages must be statically evaluate-able for extraction."

### ISSUE THREAD

**Issue by n-sviridenko** [formatjs/babel-plugin-react-intl#119]
Hello,

I'm trying to extract messages from the following file:

```js
import React from 'react';
import PropTypes from 'prop-types';
import { defineMessages, FormattedMessage } from 'react-intl';
import upperFirst from 'lodash/upperFirst';

const messages = defineMessages({
  pending: {
    id: 'app.status.pending',
    defaultMessage: 'pending',
  },
});

const mapMessageByStatus = {
  pending: messages.pending,
};

function StatusName({ status, upperFirst: useUpperFirst }) {
  const { defaultMessage, ...rest } = mapMessageByStatus[status];
  const finalDefaultMessage = useUpperFirst ? upperFirst(defaultMessage) : defaultMessage;

  return <FormattedMessage defaultMessage={finalDefaultMessage} {...rest} />;
}

StatusName.propTypes = {
  status: PropTypes.string.isRequired,
  upperFirst: PropTypes.bool.isRequired,
};

StatusName.defaultProps = {
  upperFirst: true,
};

export default StatusName;
```

But I have the following error:

```
[React Intl] Messages must be statically evaluate-able for extraction.
```

I found just one issue related to my problem (https://github.com/yahoo/babel-plugin-react-intl/issues/56). But it doesn't work with already added `defineMessages`.

What could it be?

--

```
{
  "react-intl": "2.1.5",
  "babel-plugin-react-intl": "^2.3.1"
}
```

Extractor: https://github.com/react-boilerplate/react-boilerplate/blob/master/internals/scripts/extract-intl.js

**Comment by n-sviridenko** [comment]
pind @ericf

**Comment by Billy-** [comment]
I am also having this issue with a similar use-case. This error should at most be a warning, or ideally not happen at all. I think it's acceptable to assume that people are aware that this plugin cannot extract messages from non statically evaluate-able code.

**Comment by Billy-** [comment]
Apart from the above use-case of dynamic use of `<FormattedMessage />`, there is also the following use-case, to enable re-using of messages around your app:
```js
// globalStrings.js
import { defineMessages } from 'react-intl'

export default defineMessages({
  someReusableMessage: { /* ... */ },
})

```
```jsx
/// Component.jsx
import globalStrings from './globalStrings'

// ...
    <FormattedMessage {...globalStrings.someReusableString]
// ...
```

**Comment by n-sviridenko** [comment]
@Billy, have you resolved your issue?

**Comment by Billy-** [comment]
Not solved, but worked around. The work-around is to use `defineMessages()` and `injectIntl` + `intl.formatMessage()`

**Comment by n-sviridenko** [comment]
@Billy, thanks for suggestion. Finally, the problem is in the component name. You can just pust `<FormattedMessage />` inside a HOC proxy and it will also work:

```
import React from 'react';
import { FormattedMessage } from 'react-intl';

// temporary workaround (see https://github.com/yahoo/babel-plugin-react-intl/issues/119)
function FormattedMessageFixed(props) {
  return <FormattedMessage {...props} />;
}

export default FormattedMessageFixed;
```

**Comment by chapati23** [comment]
same issue, thanks for the workaround suggestion @n-sviridenko, works for me

**Comment by longlho** [comment]
The reason for this issue is that this relies on static params to make sure things like `defaultMessage: 'foo' + someVar` gets detected and thrown (bc during extraction variables are not valid).
