### ISSUE TITLE
prefix message ids

### ISSUE THREAD

**Issue by davidyorr** [formatjs/babel-plugin-react-intl#120]
we're using multiple components in separate projects and then combining the messages into a single file in the main application. so as another way to avoid duplicate ids, it's useful to prefix the message ids. would having that as an option be something that you'd want contributed to this repo?

https://github.com/davidyorr/babel-plugin-react-intl/commit/1c2f602a517816895c67947fdad15ad9f8845284#diff-1fdf421c05c1140f6d71444ea2b27638

**Comment by longlho** [comment]
`overrideIdFn` should allow u to specify your id generation now
