### ISSUE TITLE
transform-react-inline-elements plugin

### ISSUE THREAD

**Issue by DaryaTarasowa** [formatjs/babel-plugin-react-intl#127]
Hi guys, I'm really a newbie here. I've just noticed that using this plugin for babel prevents the babel-intl-react-intl from collecting FormattedMessages (while the definedMessages are still being collected). Is it a bug or a feature?)

**Comment by eddiewang** [comment]
@DaryaTarasowa do you have any updates on this? I'm experiencing the same issue.

**Comment by longlho** [comment]
It's an issue w/ babel plugin ordering where react-inline-element might hoist/mangle elements.
