### ISSUE TITLE
[discussion] Improve plugin and develop tooling to simplify i18n workflow

### ISSUE THREAD

**Issue by SleepWalker** [formatjs/babel-plugin-react-intl#128]
Hello,

I love the way `react-intl` works and the thousands of stars on github are saying, that I'm not the only one. But there is one problem with `react-intl`. It is clear how to use it in your app files, but there is almost no info and recommendations about how to organize the whole translation flow.

The only thing, that exists is `babel-plugin-react-intl`, which outputs unusable file structure (at least for me), because this structure is easier to achieve due to the way the files are transpiled. I have a desire to develop the tools, that will allow to create the whole translation flow without much effort and will free developers from the routine of managing translations as much as possible.

According to my current experience, it looks like, the messages should be split by features/pages (not components) and grouped by locale name, e.g.:

* en
  * default.json
  * blog.json
  * videos.json
* fr
  * default.json
  * blog.json
  * videos.json

Then, when you have such structure, you can load `default.json` with your top level context provider and then load other messages on demand. Here can be two ways to do this:

* you may re-render top context provider with merged and updated combination with messages, e.g. `{ ...enDefaultJson, ...enBlogJson }`
* or you can wrap you feature into it's own provider, which will free you from merging and also isolate feature translations from the rest of the app (this is the way, which I currently prefer)

As for now I have copy-pasted your plugin and implemented an alternative mode (this means, that the plugin is still backwards-compatible), that allows me to generate the file structure, I've shown above. I have also added a feature to specify the function, that will format the exported files. The idea is to allow you control how to format outputted files, e.g. as key-value, or key-object or even save them in *.po format.

What currently lacks is that plugin must be run as a separate command (not in watch mode with webpack), because current not-so-smart implementation will not guaranty that the files won't be messed up with the strings, that was removed during codding session, but it is possible to improve implementation to support watch mode too (I think so for now). This is, probably not all the things, I want, because ideally the goal is to allow 'zero configuration' flow.

And here is actually the question: @ericf, will you accept all this things as a PR or I should better start a new project?

**Comment by sergioviniciuss** [comment]
I'd love to see if it works for me, because everything is pointing to this direction

**Comment by SleepWalker** [comment]
@sergioviniciuss I've created the PR with basic implementation. I will also publish my fork on npm, because it seems, that this repo is not being maintained anymore.

**Comment by SleepWalker** [comment]
It is published [https://www.npmjs.com/package/@sleepwalker/babel-plugin-react-intl](here).

I'm using it with the following .babelrc:

```json
...
  "env": {
    "i18n": {
      "plugins": [
        [
          "@sleepwalker/babel-plugin-react-intl",
          {
            "messagesDir": "./build/messages/",
            "moduleSourceName": "app/i18n",
            "enforceDefaultMessages": false,
            "componentNames": ["default"],
            "messagesStructure": "category"
          }
        ]
      ]
    }
  }
...
```

I'm using this plugin only to collect the messages. So won't run against the code while in build or watch mode. I'm using the following command to collect the messages:

```bash
$ rimraf ./build/messages && BABEL_ENV=i18n babel packages/app --out-file /dev/null && babel-node internal/scripts/i18n-update
```

The plugin generates json files in build directory, which then are processed by `internal/scripts/i18n-update` (this script is currently private) and merged with an actual messages, that are stored in git.

With this plugin I can write the following code, that will be successfully parsed:

```js
<Message id="foo.bar" />
{intl.formatMessage({ id: 'foo.bar' })}
```

**Comment by longlho** [comment]
close due to stale
