### ISSUE TITLE
Generate Message ID

### ISSUE THREAD

**Issue by grebenyuksv-preply** [formatjs/babel-plugin-react-intl#133]
Dear maintainers, thanks for the great job you do. I'm about to use react-intl in a mid-size project where we've been managing 10+ locales with gettext. Similarly to that, I think it would make sense for us to use a combination of `description` and `defaultMessage` as a unique message identifier (`defaultMessages` becomes `msgid` in our `.po` files, `description` becomes `msgctx`) — looks like it's the recommended way of translating same strings differently depending on the context, but ID seems totally synthetic in that case. 

Thus, do you think it would make sense for us to generate the `id` with some babel transform based on `description` and `defaultMessage`? Have you ever had such use cases? I might have to choose between contributing to `react-intl`, to [babel-plugin-react-intl-auto](https://github.com/akameco/babel-plugin-react-intl-auto), or to do that in a separate project? 

Does this all make any sense? I'd highly appreciate any kind of advice from you. Thanks for you kind attention.

**Comment by longlho** [comment]
fixed by #162
