### ISSUE TITLE
Only defineMessages works. FormattedMessage is ignored.

### ISSUE THREAD

**Issue by eddiewang** [formatjs/babel-plugin-react-intl#141]
I'm currently having problems getting this plugin to extract FormattedMessage components. It seems like this plugin only wants to run when defineMessages is involved.

I'm currently using ts-node-dev to compile, and I have the plugin defined in .babelrc

Any guidance on this matter would be greatly appreciated! Thank you.

**Comment by eddiewang** [comment]
@dabosin yes, I do.

**Comment by lzhuor** [comment]
Hi, I encountered the same problem before. Please kindly check your babel plugins confi in webpack. 

What I did to fix the problem is that I wrote a stand-alone script to extract messages so the AST will not be polluted by additional babel plugins.

**Comment by MabelCheng** [comment]
Hi, I met the same problem when running it in an electron-react app. Do you fix the problem? I tried to write a stand-alone script, but it failed. Thank you.

**Comment by lzhuor** [comment]
Hi @MabelCheng , yes I did resolve it. I put a code snippet in this issue: https://github.com/yahoo/babel-plugin-react-intl/issues/125

**Comment by eddiewang** [comment]
@lzhuor can you post what your npm script looks like? Do you have a script just for parsing the translations through `babel-plugin-react-intl`?

Also, what do you mean by setting bindings to true? Most of my components are not arrow functions, but rather `class Component extends React.Component`.

**Comment by teriteriteri** [comment]
@eddiewang hi, I'm new to react, just wondering how do we extract messages using babel-plugin-react-intl? Do we need to write a script to scan through the code which contains defineMessage and formattedMessage then save into json files? If so, what's the purpose of using babel-plugin when the script basically does all the jobs?

Thanks!!!

**Comment by longlho** [comment]
close due to stale
