### ISSUE TITLE
file.log.warn causes TypeError: Cannot read property 'warn' of undefined

### ISSUE THREAD

**Issue by jpaas** [formatjs/babel-plugin-react-intl#142]
index.js has a warning for the use for the use of FormattedPlural which is generated using `file.log.warn`

This causes an exception during babel transpilation: `TypeError: Cannot read property 'warn' of undefined`

**Comment by JoryUK** [comment]
Why has this not been merged yet?

**Comment by JoryUK** [comment]
The workaround is to use the plural syntax of the FormattedMessage instead. 
I actually even prefer this syntax.

e.g.
<FormattedMessage
id="welcome"
defaultMessage={Hello {name}, you have {unreadCount, number} {unreadCount, plural, one {message} other {messages} }}
values={{name: {name}, unreadCount}}

**Comment by longlho** [comment]
closed by #159
