### ISSUE TITLE
Am I supposed to use this plugin to obtain translation files?

### ISSUE THREAD

**Issue by arnaudriegert** [formatjs/babel-plugin-react-intl#143]
Hi

I posted [a comment](https://github.com/facebook/create-react-app/issues/1227#issuecomment-415135095)  on a `create-react-app` issue but I realize I should maybe ask the question here instead.

I used this plugin to extract all translatable strings from my app and it works fine. I have a json file for each js file that contains a translatable string, which all go in my `build/messages` directory.

However, those are not translation files: I still need to compile all the message IDs from all those files and then create a dictionary for each language, with the message IDs as keys and the translations as values, preferably each in a JSON file. I also need to update those files when I add new messages.

I found [this software](https://www.codeandweb.com/babeledit/tutorials/how-to-translate-your-react-app-with-react-intl) that does it (and seems to do it quite nicely from what I've tested) but it feels like there should be a command to automate this step.

After some research, the two closest things I found to what I am trying to do are:
- [this script](https://github.com/yahoo/react-intl/blob/master/examples/translations/scripts/translate.js) from a `react-intl` example
- and [this one](https://github.com/react-boilerplate/react-boilerplate/blob/master/internals/scripts/extract-intl.js) from `react-boilerplate`

I imagined there would be a simple command to achieve this. Am I missing something? How do people manage this usually? Do they need to compile the translations files by hand?

Thanks in advance!

**Comment by arnaudriegert** [comment]
In the meantime, I wrote [this script](https://gist.github.com/arnaudriegert/0ce380f3e5cb39faec8c0d96b2b43b9c) that does the equivalent of `msgmerge` in `gettext`: we update the JSON for each language to add the missing keys (with `""` as the initial value, to be completed by the translator) and remove the obsolete ones. The default langugage's JSON is updated with the default values from the descriptors.

Hope this helps.

**Comment by plondon** [comment]
I think most people use https://github.com/GertjanReynaert/react-intl-translations-manager to create the translation files

**Comment by longlho** [comment]
close due to stale
