### ISSUE TITLE
[Babel 7] TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by alexnez96** [formatjs/babel-plugin-react-intl#156]
### Problem

The latest `babel-plugin-react-intl` at v`3.0.1` fails with a `TypeError: Path must be a string. Received undefined`.

### Stacktrace

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.extname (path.js:1456:5)
    at PluginPass.post (/my/project/path/node_modules/babel-plugin-react-intl/lib/index.js:204:45)
    at transformFile (/my/project/path/node_modules/@babel/core/lib/transformation/index.js:94:27)
    at runSync (/my/project/path/node_modules/@babel/core/lib/transformation/index.js:45:3)
    at transformSync (/my/project/path/node_modules/@babel/core/lib/transform.js:43:38)
    at transform (/my/project/path/node_modules/@babel/core/lib/transform.js:22:38)
    ...
```

### Reproduction

```js
import fs from 'fs'
import { transform } from '@babel/core'

const presets = ['@babel/env', '@babel/react']
const plugins = ['react-intl']

const code = fs.readFileSync('path/to/file')
const { metadata } = await transform(code, { presets, plugins })
```

### Environment

OS: Ubuntu 16.04
Node: 8.12.0
NPM: 6.4.1

**Comment by alexnez96** [comment]
As a workaround, I am passing `filename` to Babel `options`, as suggested [here](https://github.com/yahoo/babel-plugin-react-intl/issues/135#issuecomment-367665562):

`const { metadata } = await transform(code, { presets, plugins, filename: 'path/to/file' })`

**Comment by redonkulus** [comment]
This is a dup of https://github.com/yahoo/babel-plugin-react-intl/issues/156. Lets discuss in that one.

**Comment by alexnez96** [comment]
What's the original again?

**Comment by redonkulus** [comment]
Sorry put the wrong one in.

**Comment by alexnez96** [comment]
Not sure if it's the same underlying problem, but just to be clear, this error happens with NodeJS API in `3.0.1`. It's thrown at https://github.com/yahoo/babel-plugin-react-intl/blob/master/src/index.js#L190 (i.e. even before `join`) because `filename` is `undefined`.

**Comment by redonkulus** [comment]
Good catch, will reopen

**Comment by longlho** [comment]
close due to stale
