### ISSUE TITLE
cache is not working properly

### ISSUE THREAD

**Issue by dabit1gamma** [formatjs/babel-plugin-react-intl#160]
For example, if you have a message like "hello" then this plugin will create it. If you change it per "hello!" it will be replaced. But if you change it again per "hello" then it will not be replaced. It's a critical bug.

Thanks

**Comment by tomek-f** [comment]
Turning off `cacheDirectory` (false) in `babel-loader` helped me a little with cache problems.

**Comment by enzoferey** [comment]
People coming here for Nextjs integration, this solved it for me:

```js
// next.config.js

// Disable `next-babel-loader` caching if production
// That way `babel-plugin-react-intl` extracts messages properly
webpack: (config, { dev, isServer }) => {
    if (!dev && !isServer) {
        config.module.rules
            .filter(rule => rule.test.test(".js"))
            .forEach(rule => {
                rule.use.options.cacheDirectory = false;
            });
    }
}
```

**Comment by longlho** [comment]
close due to stale
