### ISSUE TITLE
Having NPM install from github doesn't run the build step

### ISSUE THREAD

**Issue by toadzky** [formatjs/babel-plugin-react-intl#33]
Can we add a `preinstall` hook like the `prepublish` one that builds `lib/index.js` when the module gets installed from github? I'm not sure if there is a way to say "If it's being installed from not NPM, build it first"

**Comment by jazzido** [comment]
+1

**Comment by ericf** [comment]
Feel free to raise a PR which doesn't incur the build when it's pulled in as a normal dependency from npm. I think React Router does some heuristics to determine this…
