### ISSUE TITLE
incompatible with babel.transformFile

### ISSUE THREAD

**Issue by mattkime** [formatjs/babel-plugin-react-intl#81]
file content gets written out to the wrong json file. seems to be a problem with using babel-plugin-react-intl asynchronously. 

here's what i see - 

1.jsx 
2.jsx
3.jsx (no FormattedMessages)

2.jsx's FormattedMessages content gets output to 3.jsx's corresponding json file.

**Comment by ericf** [comment]
Can you create a simple repo that shows the issue so I can reproduce it?

**Comment by mattkime** [comment]
I'll try to put a test in a PR

**Comment by ericf** [comment]
@mattkime were you able to determine what the issue was?

**Comment by mattkime** [comment]
thanks for the reminder.

i hope to look at this in the next couple of days.

**Comment by longlho** [comment]
close due to stale
